### ISSUE TITLE
Error on checkout dropdown

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-checkout-referrals#11]
When you use Checkout Referrals with the latest version of AffWP, an error is shown on the checkout screen when using the dropdown. after saving the Integrations settings tab all was good.
I am wondering if the settings are not getting set on init.
![affwp-checkout-referrals](https://cloud.githubusercontent.com/assets/4752949/20405438/55adbf8a-ad09-11e6-978b-95c8c2438a5a.png)

**Comment by sumobi** [comment]
Closed via https://github.com/AffiliateWP/affiliatewp-checkout-referrals/commit/37d5954d2f03495c3f75b30d57222d517885927e

Pushing out a 1.0.4 release soon.
