### ISSUE TITLE
Add support for Lifetime Commissions

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-checkout-referrals#12]
It would be great to make a way for Checkout Referrals to be able to work with Lifetime Commissions.

**Comment by sumobi** [comment]
Related: https://github.com/AffiliateWP/affiliate-wp-lifetime-commissions/issues/37

**Comment by gspice** [comment]
Another request to use these together:
https://secure.helpscout.net/conversation/367648306/59572/?folderId=205529

**Comment by amdrew** [comment]
Closing this issue in favor of the original AffiliateWP/affiliate-wp-lifetime-commissions#37

**Comment by amdrew** [comment]
Actually, going to leave it open, good to have a record on both repos

**Comment by gspice** [comment]
Another:
https://secure.helpscout.net/conversation/511851222/74746/?folderId=205529

**Comment by gspice** [comment]
Another:
https://secure.helpscout.net/conversation/518124329/75515?folderId=1170842

**Comment by gspice** [comment]
https://secure.helpscout.net/conversation/544428638/78495?folderId=1170842

**Comment by tubiz** [comment]
PR: #20

**Comment by tubiz** [comment]
PR updated.

* The `affwp_checkout_referral_already_tracking_referral` filter has been removed.
* The CR affiliates list won't be displayed anymore for a logged in user that is linked to an affiliate.
* The CR affiliates list won't be displayed if an affiliate cookie exists.

Thanks to @amdrew for this: https://github.com/AffiliateWP/affiliate-wp-lifetime-commissions/issues/37#issuecomment-401988667

**Comment by tubiz** [comment]
> If the AffiliateWP - Lifetime Commissions plugin is deactivated and the logged in customer is already linked to an affiliate the CR affiliates list is not shown on the checkout page.

Fixed via e723dba

**Comment by gspice** [comment]
This works like a dream!  

Confirmed:
* The CR affiliates list won't be displayed anymore for a logged in user that is linked to an affiliate.
* The CR affiliates list won't be displayed if an affiliate cookie exists.

**Comment by amdrew** [comment]
👍 Great stuff, merged!
