### ISSUE TITLE
Add affiliate name field

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-checkout-referrals#2]
We have had several customers request that checkout referrals have a text field to enter an affiliate id or name without the selection list.

**Comment by sumobi** [comment]
:+1:

**Comment by sumobi** [comment]
first pass: https://github.com/AffiliateWP/affiliatewp-checkout-referrals/commit/9cc3f9af43043bfc35b37372dff624e39bb9be8e

**Comment by sumobi** [comment]
Added field validation, considering this done
https://github.com/AffiliateWP/affiliatewp-checkout-referrals/commit/2db7db45daf05a0e326b5360cb1d5e2da7da9b4b
