### ISSUE TITLE
CR shows at checkout if affiliate link used on checkout page

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-checkout-referrals#21]
It's possible to visit the checkout page with an affiliate link and still see Checkout Referral's select menu/input. This is because you can't set & read the cookie on the same page load. It will disappear if the page is reloaded.

<img width="578" alt="screen shot 2018-07-04 at 12 52 05 pm" src="https://user-images.githubusercontent.com/52581/42251047-1b11180a-7f89-11e8-95a9-dfa42799d4ec.png">

To fix we can look for the existence of the referral variable (as set from the options) in the URL. If it exists, hide CR. No point checking specifically for the checkout page that I can see. In the future we might decide to allow CR to work anywhere (a name change might be in order) so this will help for that also.

**Comment by tubiz** [comment]
PR: #22

**Comment by amdrew** [comment]
Works great, merged.
