### ISSUE TITLE
PHP Notice: Trying to get property 'user_nicename' of non-object

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/affiliatewp-checkout-referrals#39]
If an affiliate user account has been deleted, a PHP notice is triggered when retrieving the list of affiliates to display in the select field.

**Comment by tubiz** [comment]
PR: #40

**Comment by DrewAPicture** [comment]
Fixed in 149a1fd25bc2e243e4928d39c4697ff3fe2a6074 for `release/1.0.9`
