### ISSUE TITLE
Move settings to dedicated tab

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-checkout-referrals#41]
Like other add-ons, Checkout Referrals should really have its own settings tab. Currently the plugin's options are shown on AffiliateWP's Integrations tab:

<img width="735" alt="Screen Shot 2021-01-08 at 9 55 37 AM" src="https://user-images.githubusercontent.com/52581/103944931-3f5f7a00-5199-11eb-8dc4-af77a3700d5c.png">

The grand plan however would be to have all our add-on settings merged together in one easy to find location, but for now, a tab is better than the options being under integrations.

**Comment by DrewAPicture** [comment]
@dbeja Go ahead and tackle this one in addition to #15 and we'll target both for 1.0.9.

**Comment by dbeja** [comment]
PR: #44

**Comment by dbeja** [comment]
Merged #44 against `release/1.0.9`.
