### ISSUE TITLE
Typo in Checkout Referrals in admin settings

### ISSUE THREAD

**Issue by lisag** [AffiliateWP/affiliatewp-checkout-referrals#6]
There is a typo in the WordPress admin settings for Checkout Referrals: https://cloudup.com/ctrh6PNgrsR

Where the **Affiliate Display** radio buttons are, the top one says "User Nicename". I imagine this is supposed to be "Nickname".

**Comment by michaelbeil** [comment]
I am wondering if we should just reword the User nicename option to Username and remove the nickname option as the username and nickname are generally the same. I suppose the nickname can be changed by the affiliate, though. 

Nicename was used here: https://github.com/AffiliateWP/AffiliateWP/issues/843#issuecomment-145653679, however it does not seem to be widely used elsewhere.

**Comment by amdrew** [comment]
It's intended to be user nicename, not username. Will circle back to this issue, it could probably still be improved.

**Comment by amdrew** [comment]
Closing this issue as I'm not seeing any way this can be improved. As per my comment above, the spelling is intentional to match WP.
